public class testClass {
    //Look at me I'ma code!
    //Branching business
    public testClass() {
    	//Master commit
    	myobj__c obj = new myobj__c(newField__c = 'test');
    }
    
    
    public static void doAThing() {
    	//Test feature commit
    }
    
    public void localThing() {
    	//Auto-deployment test
    	//2
    }
    
    public void remoteCommit() {
        //Someone else's commit
    }
    
    public static void patch() {
    	//I am patch
    	//patch me
    }
    
    //Remote edit
}
