/**
* This class is used to define constant values used across the application
*/
public class ApplicationConstantHelper {
	
 /**
 * Roles and Responsibilities Role__c pick list values
 */
 	public static final String ROLEARESP_ROLE_PROGRAM = 'program';
 	public static final String ROLEARESP_ROLE_FISCAL = 'fiscal';
 	public static final String ROLEARESP_ROLE_GRANT = 'grant';
 	public static final String ROLEARESP_ROLE_OTHER = 'other';
 	
  /**
 * Roles and Responsibilities BizRole__c pick list values
 */
 	public static final String ROLEARESP_BIZ_ROLE_PROJECT_DIRECTOR = 'Project Director';
 	public static final String ROLEARESP_BIZ_ROLE_EBIZ_POC = 'EBIZ POC';
    
}