public with sharing class BudgetWrapper {
	public BudgetWrapper() {

	}

	public String programName {get; set;}
	public String subRecipientName {get; set;}
	public String awardAmount {get; set;}
	public String uniqueKeyFormula {get; set;}
	public String programCode {get; set;}
	public String objectCode {get; set;}
	public String leaId {get; set;}
	public String subRecipientId {get; set;}
	public String programId {get; set;}
	public String keyContactId {get; set;}

}