@isTest(seealldata=false)
private with sharing class FOALeadViewCtrlTest {

    static testMethod void testController() {
    /*
        Account acct = null;
      
        User u = new User(Id=UserInfo.getUserId());
        System.runAs(u){
            GNT__KeyValueStore__c key= new GNT__KeyValueStore__c(Name='ENTERPRISE',GNT__BooleanValue__c=true);
            AccountTriggerHelper.skipTrigger=true;
            acct = TestHelper.getAccount(true);
        }   
       
        Test.startTest();
        ApexPages.CurrentPage().getParameters().put('Id',acct.id);
        ApexPages.StandardController sc = new ApexPages.standardController(acct);
        FOALeadViewCtrl ctrl = new FOALeadViewCtrl(sc);
        ctrl.getKeyValueMap();
        Test.stopTest();
        
        System.assertNotEquals(ctrl.getKeyValueMap(),null);
        ctrl.deleteURL = Page.KeyPerformanceIndicatorView;
        
        */
    }
 
}