/**
* IntegCGIAdv_ProgPhaseBudget_DeleteFile is used to produce the JSON for deleting Program/Phase/Budget
* association files
*
* CHANGE HISTORY
* ==================================================================================================
* Date              Name                Description
* Mar 01 2018       Brian Mason         Created
* ==================================================================================================
*/
public class IntegCGIAdv_ProgPhaseBudget_DeleteFile extends IntegCGIAdv_DeleteFiles_Wrapper {
	// PUBLIC CONSTRUCTORS
    public IntegCGIAdv_ProgPhaseBudget_DeleteFile(){ super(); }
    public IntegCGIAdv_ProgPhaseBudget_DeleteFile( String file ){ super( file ); }
}