/**
* IntegCGIAdv_IET_DeleteFile is used to produce the JSON for deleting IET files
*
* CHANGE HISTORY
* ==================================================================================================
* Date              Name                Description
* Mar 01 2018       Brian Mason         Created
* ==================================================================================================
*/
public class IntegCGIAdv_IET_DeleteFile extends IntegCGIAdv_DeleteFiles_Wrapper {
	// PUBLIC CONSTRUCTORS
    public IntegCGIAdv_IET_DeleteFile(){ super(); }
    public IntegCGIAdv_IET_DeleteFile( String file ){ super( file ); }
}