/**
* IntegCGIAdv_Program_DeleteFile is used to produce the JSON for deleting Program files
*
* CHANGE HISTORY
* ==================================================================================================
* Date              Name                Description
* Mar 01 2018       Brian Mason         Created
* ==================================================================================================
*/
public class IntegCGIAdv_Program_DeleteFile extends IntegCGIAdv_DeleteFiles_Wrapper {
	// PUBLIC CONSTRUCTORS
    public IntegCGIAdv_Program_DeleteFile(){ super(); }
    public IntegCGIAdv_Program_DeleteFile( String file ){ super( file ); }
}