@isTest(SeeAllData=false)
public class OrganizationViewCtrlTest {
    static testMethod void someTest() {
    /*
     AccountTriggerHelper.skipTrigger = true;
         Account acc = TestHelper.getAccount(true);    
         ApexPages.StandardController sc = new ApexPages.standardController(acc);
         ApexPages.currentPage().getParameters().put('id',acc.Id);
         OrganizationViewCtrl e = new OrganizationViewCtrl(sc);
         e.getKeyValueMap();
         */
    }
     
}