/*
    All code for Trigger on Roles and Responsibilities Object
    ***********************************************************
    Audit History
    ***********************************************************
    05/29/2015      Ramu Loke             Created
    08/30/2015      Vinayak Sharma        Edited
    ***********************************************************
*/
public with sharing class RolesandResponsibilitiesTriggerHelperOld extends GNT.TriggerHelper {
//temp
}