@isTest
public class SelectRecordsPopUpCtrlTest {
    static testMethod void someTest1() {
    /*
        AccountTriggerHelper.skipAll = true;
        Account a = TestHelper.getAccount(true);
        ApexPages.currentPage().getParameters().put('flextable',a.id);
        ApexPages.currentPage().getParameters().put('parentId',a.id);
        ApexPages.currentPage().getParameters().put('type','ProgramFA');
        SelectRecordsPopUpCtrl e = new SelectRecordsPopUpCtrl();
        e.getKeyValueMap();
        e.getListParameters();
        */
    }
    static testMethod void someTest2() {
    /*
        AccountTriggerHelper.skipAll = true;
        Account a = TestHelper.getAccount(true);
        ApexPages.currentPage().getParameters().put('flextable',a.id);
        ApexPages.currentPage().getParameters().put('parentId',a.id);
        ApexPages.currentPage().getParameters().put('type','ProgramSA');
        SelectRecordsPopUpCtrl e = new SelectRecordsPopUpCtrl();
        e.getKeyValueMap();
        */
    }
    static testMethod void someTest3() {
    /*
        AccountTriggerHelper.skipAll = true;
        Account a = TestHelper.getAccount(true);
        ApexPages.currentPage().getParameters().put('flextable',a.id);
        ApexPages.currentPage().getParameters().put('parentId',a.id);
        ApexPages.currentPage().getParameters().put('type','AnnouncementFA');
        SelectRecordsPopUpCtrl e = new SelectRecordsPopUpCtrl();
        e.getKeyValueMap();
        */
    }
    static testMethod void someTest4() {
    /*
        AccountTriggerHelper.skipAll = true;
        Account a = TestHelper.getAccount(true);
        ApexPages.currentPage().getParameters().put('flextable',a.id);
        ApexPages.currentPage().getParameters().put('parentId',a.id);
        ApexPages.currentPage().getParameters().put('type','FedPrograms');
        SelectRecordsPopUpCtrl e = new SelectRecordsPopUpCtrl();
        e.getKeyValueMap();
        */
    }
    static testMethod void someTest5() {
    /*
        AccountTriggerHelper.skipAll = true;
        Account a = TestHelper.getAccount(true);
        ApexPages.currentPage().getParameters().put('flextable',a.id);
        ApexPages.currentPage().getParameters().put('parentId',a.id);
        ApexPages.currentPage().getParameters().put('type','AwardFA');
        SelectRecordsPopUpCtrl e = new SelectRecordsPopUpCtrl();
        e.getKeyValueMap();
        */
    }
    static testMethod void someTest6() {
    /*
        AccountTriggerHelper.skipAll = true;
        Account a = TestHelper.getAccount(true);
        ApexPages.currentPage().getParameters().put('flextable',a.id);
        ApexPages.currentPage().getParameters().put('parentId',a.id);
        ApexPages.currentPage().getParameters().put('type','StrategicPlanSA');
        SelectRecordsPopUpCtrl e = new SelectRecordsPopUpCtrl();
        e.getKeyValueMap();
        */
    }
    static testMethod void someTest7() {
    /*
        AccountTriggerHelper.skipAll = true;
        Account a = TestHelper.getAccount(true);
        ApexPages.currentPage().getParameters().put('flextable',a.id);
        ApexPages.currentPage().getParameters().put('parentId',a.id);
        ApexPages.currentPage().getParameters().put('type','ProgramBC');
        SelectRecordsPopUpCtrl e = new SelectRecordsPopUpCtrl();
        e.getKeyValueMap();
        */
    }
   
}