@isTest
private class TestFINETSubmissionHelper {

    static testMethod void myUnitTest() {
    /*
        AccountTriggerHelper.skipAll = true;
        Account a= TestHelper.getAccount(true);
        r_mjr_prog__c mjrprg=TestHelper.getMajorProgram(true);
        r_prog__c program=TestHelper.getr_prog(true,mjrprg.Id,a.Id);
        Test.startTest();
      ApexPages.currentPage().getParameters().put('Id',program.Id);
       FINETSubmissionHelper progcreate=new FINETSubmissionHelper();
       progcreate.whenClicked();
       //FINETSubmissionHelper.webCallout('www.google.com');
        Test.stopTest();
        */
    } 
}