@isTest
private class TestQualifyAnnouncementViewHelper {

    static testMethod void myUnitTest() {
    /*
        AnnouncementTriggerHelper.skipTrigger = true;
        User u = TestHelper.getAdminUser(true);
        System.runAs(u) {
            Announcement__c ann = TestHelper.getAnnouncement(true);
            List<String> selectedRecordIds = new List<String>();
            selectedRecordIds.add(ann.id);
            StrategicPlan__c obj = TestHelper.getStrategicPlan(true);
            OpportunityQualification__c oppqual = new OpportunityQualification__c(FundingOpportunity__c = ann.id);
            insert oppqual;
            
            QualifyAnnouncementViewHelper qualifyannhelper = new QualifyAnnouncementViewHelper();
            qualifyannhelper.selectedRecordIds = selectedRecordIds;
            qualifyannhelper.clickHandler(); 
            qualifyannhelper.qualifyAnnouncements(selectedRecordIds);           
        }
    */
    }
}