@isTest
private with sharing class TestDashboardApplicationMapHelper{
    static testMethod void testgetPins() {
    /*
          UserTriggerHelper.skipTrigger = true;
          User u = TestHelper.getAdminUser(true);
          System.runAs(u){
               
              GNT__KeyValueStore__c key= new GNT__KeyValueStore__c(Name='ENTERPRISE',GNT__BooleanValue__c=true);
              AccountTriggerHelper.skipTrigger=true;
              Map<String,string> urlParams = new Map<String,String>();
              
              Account acct = TestHelper.getAccount(true);
              AnnouncementTriggerHelper.skipTrigger = true;
              Announcement__c ann = TestHelper.getAnnouncement(false);
              ann.FiscalYear__c=GNT.AppUtils.getCurrentFiscalYear();
              insert ann;
              
              
              ApplicationTriggerHelper.skipTrigger = true;
              Application__c app = TestHelper.getApplication(ann.Id,false);
              app.ExternalOrganization__c=acct.Id;
              insert app;
               
              Test.startTest();
              DashboardApplicationMapHelper ctrl = new DashboardApplicationMapHelper();
              ctrl.getPins(urlParams);
              Test.stopTest();
          }
        */
    }
    
}