@isTest
private with sharing class TestNoteAddCtrl{
 /*   static testMethod void testaddAttachment() {
       
          User u = TestHelper.getAdminUser(true);
          System.runAs(u){
          
              AnnouncementTriggerHelper.skipTrigger = true;
              Announcement__c ann = TestHelper.getAnnouncement(true);
              
              Note tempNote = new Note();
              tempNote.ParentId = ann.Id;
              tempNote.Title = 'Test';
              tempNote.Body ='Test Body';
              insert tempNote;
            
               
              Test.startTest();
              ApexPages.currentPage().getParameters().put('parentId',ann.id);
              NoteAddCtrl ctrl = new NoteAddCtrl();
              ctrl.classificationVal = 'Test Val';
              ctrl.addAttachment();
              Test.stopTest();
          }
        
    }*/
}