@isTest
private class TestObsoleteFieldCodeFinderBatch {
    
    @isTest static void test_method_one() {
    /*
        User u = TestHelper.getAdminUser(true);
        system.runAs(u) {
            Test.startTest();
            List<BusinessObject__c> updateList=new List<BusinessObject__c>();
            BusinessObject__c ck=new BusinessObject__c(name='UserRegistration__c');
            updateList.add(ck);
            insert updateList;
            ObsoleteFieldCodeFinderBatch ctrl= new ObsoleteFieldCodeFinderBatch();
            Database.executeBatch(ctrl);
            Test.stopTest();
        }
        */
    }
    
}