@isTest
private class TestProgressReportViewCtrl{

    static testMethod void testWhenClicked1() { 
    /*
      User u = TestHelper.getAdminUser(true);
        System.runAs(u) {
     AccountTriggerHelper.skipTrigger=true;
     GrantTriggerHelper.skipTrigger=true;
     AwardTriggerHelper.skipTrigger=true;
     RolesAndResponsibilitiesTriggerHelper.skipTrigger=true;
        //Test.startTest();
       // FOALead__c fOALead = TestHelper.getFOALead(true);
        Grant__c g = TestHelper.getGrant(true);
       
       Award__c a = TestHelper.getAwards(g.ID,true);
       TermCondition__c tc = TestHelper.getTermCondition(true,'Progress Report');
      
       ProgressReports__c prc = new ProgressReports__c();
       prc.TermandCondition__c = tc.id;
       prc.Award__c = a.id;
       insert prc;
         Test.startTest();
         ApexPages.currentPage().getParameters().put('Id',prc.Id);
         
         ApexPages.StandardController sc = new ApexPages.standardController(prc);
         ProgressReportViewCtrl pr= new ProgressReportViewCtrl(sc); 
         pr.getKeyValueMap();
      
       
        Test.stopTest();      
    }
    */
    }
    
    static testMethod void testWhenClicked2() {
    /*
      User u = TestHelper.getAdminUser(true);
        System.runAs(u) {
     AccountTriggerHelper.skipTrigger=true;
     GrantTriggerHelper.skipTrigger=true;
     AwardTriggerHelper.skipTrigger=true;
     RolesAndResponsibilitiesTriggerHelper.skipTrigger=true;
        //Test.startTest();
       // FOALead__c fOALead = TestHelper.getFOALead(true);
        Grant__c g = TestHelper.getGrant(true);
       
       Award__c a = TestHelper.getAwards(g.ID,true);
       //TermCondition__c tc = TestHelper.getTermCondition(true,'Fiscal');
       TermCondition__c tc = TestHelper.getTermCondition(true,'Progress Report');
      
       ProgressReports__c prc = new ProgressReports__c();
       prc.TermandCondition__c = tc.id;
       prc.Award__c = a.id;
       insert prc;
         Test.startTest();
         ApexPages.currentPage().getParameters().put('Id',prc.Id);
         
         ApexPages.StandardController sc = new ApexPages.standardController(prc);
         ProgressReportViewCtrl pr= new ProgressReportViewCtrl(sc); 
         pr.getKeyValueMap();
      
       
        Test.stopTest();      
    }
    */
    }
     
}