@isTest(SeeAllData=true)
private class TestFlexTableDataCleanupBatch {
    
    @isTest static void test_method_one() {
    /*
        User u = TestHelper.getAdminUser(true);
        system.runAs(u) {
            Test.startTest();
            FlexTableDataCleanupBatch ctrl= new FlexTableDataCleanupBatch();
            Database.executeBatch(ctrl);
            Test.stopTest();
        }
        */
    }
    
}