@isTest
private class TestStrategicPlanProgramEditCtrl{
   
      static testMethod void testController() {  
      /*
          UserTriggerHelper.skipTrigger=true;
          User u = TestHelper.getAdminUser(true); 
        
          System.runAs(u){
            
             AccountTriggerHelper.skipAll = true;
             StrategicPlan__c stratPlan = TestHelper.getStrategicPlan(true);
          
              Test.startTest();
              ApexPages.StandardController sc = new ApexPages.standardController(stratPlan);
              ApexPages.CurrentPage().getParameters().put('id',stratPlan.Id);
              ApexPages.CurrentPage().getParameters().put('StrategicPlanid',stratPlan.Id);
              StrategicPlanProgramEditCtrl ctrl= new StrategicPlanProgramEditCtrl(sc);
              ctrl.getKeyValueMap();
              Test.stopTest();
        }
    */
   }
   
}