@isTest
private class TestFINETProgCreatHelper {

       static testMethod void myUnitTest() {
       /*
        GNT.UserPreferenceHelper.setStringValue('ActiveAppName__c','StateasGrantor');
        AccountTriggerHelper.skipAll = true;
        Account a= TestHelper.getAccount(true);
        r_mjr_prog__c mjrprg=TestHelper.getMajorProgram(true);
        r_prog__c program=TestHelper.getr_prog(true,mjrprg.Id,a.Id);
        
        Test.startTest();
        ApexPages.currentPage().getParameters().put('Id',program.Id);
        FINETProgCreatHelper progcreate=new FINETProgCreatHelper();
        progcreate.whenClicked();
        Test.stopTest();
            */
       } 
}