@isTest
private class TestLightningSelfRegisterController {
    
    @isTest static void test_method_one() {
    /*
        AccountTriggerHelper.skipTrigger = true;
        Account a = TestHelper.getAccount(true);
        LightningSelfRegisterController.isValidPassword('test', 'test');
        LightningSelfRegisterController.siteAsContainerEnabled('http://a.com');
        LightningSelfRegisterController.selfRegister('test' ,'test', 'test@test.com','test', 'test', a.Id, 'http://a.com', null, 'http://a.com', true);
        LightningSelfRegisterController.selfRegister('test' ,'test', 'test@test.com','test', 'test', a.Id, 'http://a.com', 'test', 'http://a.com', true);
        LightningSelfRegisterController.calculate(1);
        */
    }
    
    @isTest static void test_method_two() {
        // Implement test code
    }
    
}