@isTest
private with sharing class TestTaskscheduleGroupEditCtrl{
    static testMethod void testController() {
    /*
          Account acct = null;
          User u = TestHelper.getAdminUser(true);
          TaskSchedule__c tskSch = null;
          System.runAs(u){
            GNT__KeyValueStore__c key= new GNT__KeyValueStore__c(Name='ENTERPRISE',GNT__BooleanValue__c=true);
            AccountTriggerHelper.skipTrigger=true;
            TaskTriggerHelper.skipTrigger = true;
            acct = TestHelper.getAccount(true);
            tskSch = new TaskSchedule__c();
            insert tskSch;
        }   
         
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.standardController(tskSch);
        ApexPages.currentPage().getParameters().put('id',tskSch.id);
        TaskScheduleGroupEditCtrl ctrl = new TaskScheduleGroupEditCtrl(sc);
        Test.stopTest();
        */
    }
}