@isTest
private class TestFINETProgramViewCtrl {
    @isTest static void test_method_one(){
    /*
        AccountTriggerHelper.skipAll = true;
        Account a= TestHelper.getAccount(true);
        r_mjr_prog__c mjrprg=TestHelper.getMajorProgram(true);
        r_prog__c program=TestHelper.getr_prog(true,mjrprg.Id,a.Id);
        
        Test.startTest();
            ApexPages.currentPage().getParameters().put('Id',program.Id);
            ApexPages.StandardController stdController = new ApexPages.StandardController(program);
            FINETProgramViewCtrl finetProgramNewCtrl = new FINETProgramViewCtrl(stdController);
            FINETProgramViewCtrl.getKeyValueMap();
        Test.stopTest();
        */
    } 
    
}