@isTest
private with sharing class TestSimpleDynamicController{
    static testMethod void testController() {
       /*
          User u = TestHelper.getAdminUser(true);
          Account acct = null;
          System.runAs(u){
              
              GNT__KeyValueStore__c key= new GNT__KeyValueStore__c(Name='ENTERPRISE',GNT__BooleanValue__c=true);
              AccountTriggerHelper.skipTrigger=true;
              acct = TestHelper.getAccount(true);
              
              Test.startTest();
              SimpleDynamicController ctrl = new SimpleDynamicController();
              ctrl.getDynamicDetail();
              Test.stopTest();
          }
        */
    }
}